os: osx
osx_image: xcode11
script:
- node --version
- xcodebuild -version
- HOMEBREW_NO_AUTO_UPDATE=1 brew install mysql
- brew services start mysql
- sleep 10
- mysql -uroot
- mysql -uroot  -e "CREATE DATABASE auth_session;"
- mysql -uroot --password=root -e "set global max_connections = 10000;"
- cd backend/ && npm i -d && ./node_modules/.bin/tsc -p tsconfig.json
- cd backend/ && TEST_MODE=testing node build/index.js &

branches:
  only:
  - master
notifications:
  slack:
    secure: GGVzhnCu2C2iyeapPChm0SZil6i4QrgwFIprAgV/o5MOeslfQNbWiVnXcTjo++UsmxQ4Gcp4QNJ3CgsQhIE1wQI16Vbbtu1ZdELoZHGipC7p8XxpDWmnVrq7a0WhxZ449NIA3Si439GGLjbFoVEdTNOh4fO4/wW9Rd5OJ0vJ8eO8AZI8CC8Jwk8qhwZi8p+2DYtO7j+5t2LaYl1+NcIL7lgvVquqszdBauzwo68CQ5Gi+dJ5fY4Slsty05etnQyjc3AyZ2rKx7rtVSeV+NTpsGgwc/F3l1IXwQeBfwIRsBK9M00Z5IEIKQktgKf+OuXJaiwp7GNxjbXSqEG1jI7hvqy7FyRZIrYb4rPjxwXWRP6hU8aZLNPjmNJCDceyMvoVXdgEk+IqTWVmWx4Ih+MtvlVWpk0fQnxL3UsgzRUkP2nK4gZDjowZ6CNI3xXlTy5Fpq2dZ1ZDTDMxOzhYwzmtJf4bWG5gAj08pQaumXutreCCmBvqBpkJ+LUY0FKMXG2iaVzIrhmX/yD8I9XR/8lh5EucctZ/nCOyJHHMkOoDq7XC5GcuKP7c38h96OaZBmGwAkdyiGi+IhGojJu2H2ZioHxybG+qFsjSsAoY1F8tJvkP496kBlfmEqrbz6H2g12j/RhCMKDKYRZHVKtj0SCW0BU3t68Za4p1yqkLbQoJ4vk=
