os: osx
osx_image: xcode11
jobs:
  include:
  - stage: test
    if: tag =~ ^dev-v[0-9]+(\.[0-9]+)*$
    script:
    - cd ../
    - wget -q https://download.java.net/java/GA/jdk12.0.2/e482c34c86bd4bf8b56c0b35558996b9/10/GPL/openjdk-12.0.2_osx-x64_bin.tar.gz
    - tar -xzf openjdk-12.0.2_osx-x64_bin.tar.gz
    - export JAVA_HOME=`pwd`/jdk-12.0.2.jdk/Contents/Home
    - cd supertokens-ios
    - echo -e "$BITBUCKET_SSH" >> ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - "echo -e \"Host\t\tbitbucket.org\\nHostname\tbitbucket.org\\nIdentityFile\t~/.ssh/id_rsa\\nUser\t\trishabh-poddar\"
      >> ~/.ssh/config"
    - echo -e "StrictHostKeyChecking no\n" >> ~/.ssh/config
    - HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install mysql@5.6
    - brew link --force mysql@5.6
    - export PATH=$PATH:/usr/local/Cellar/mysql@5.6/5.6.46/bin
    - brew services start mysql@5.6
    - sleep 10
    - mysql -u root  -e "CREATE DATABASE auth_session;"
    - mysql -u root -e "set global max_connections = 10000;"
    - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root');"
    - brew services restart mysql@5.6
    - sleep 10
    - HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install jq
    - cd .circleci && ./doTests.sh
  - stage: deploy
    if: tag =~ ^v[0-9]+(\.[0-9]+)*$
    script:
    - gem install cocoapods -v 1.8.4
    - pod install
    - export COCOAPODS_TRUNK_TOKEN=$COCOAPODS_TOKEN
    - pod lib lint SuperTokensSession.podspec --verbose
    - pod trunk push SuperTokensSession.podspec --verbose
notifications:
  slack:
    secure: lI5DdJYBeRHvHBGbTE7jr5eV4Epxt/KuCdNgAgU5+7OwOmyORWKGzrz5qR42TyFvkhbbdcRIwRDmC72pawQbooptOAqCtZYgY+FNVLqA+bRPlQqn2K7neouCgJC+eZmvn57DtSsBNFULVuiDHJ00tKH6xd5unlLo8JApP9QX7gw/JjiOrKuZj4ekoO5vtAkot8IZEFCLgHyIDnracziWfzdt/toiyW3Ehe62oGkJW8iViCsm5+c+657AJTacYf6j4cN5/q0up1YfeaiZXzn0lKCzFKkH4gr783ujmb5wQKFA/tOdQHpoKWFWztHUs1Ndgp8pVpye/wBpugNl+PJGnhrMhWnZD1DRz0cesg40TE+MfR2VOoBSwYmwWX6brX9AE44fRdWNrndkkS+ci2KyXC0cyEha3hWgLzcBHdFwWSV7sK4NuIlCezeVXlp744s22/PyCXUrlt3xwBl827opqNuxmgOQ4uJ3D4cxYgtqzDHB3KI+x1STmISj0teS/+IyXCzyvsOPkZgFlcvQ5AIGT2UClE+MhzzJcNkrzo5FmZGojozMkDjZud83r5p+SzQ6rn5fT8X1TxvsiaKrKDokUiVSUv4Hsf01WFt+skAMC7AkmWZMBZi60mlXwnDmCJIfW2eyVwIZaBjmEZuc2mKywfOhdCdj9peON8xpR62gjvQ=
